#!/usr/bin/env node
// Quantum Design tokens — build (DTCG JSON → CSS custom properties) and audit.
// Zero dependencies, Node >= 18. Copy this file into the project; the JSON stays the
// single source of truth and the CSS it writes is never edited by hand.
//
//   node quantum-tokens.mjs build [--src tokens] [--out tokens/design-tokens.css]
//   node quantum-tokens.mjs audit [--src tokens] [--scan src]... [--exempt path]...
//                                 [--strict] [--verbose]
//   node quantum-tokens.mjs match [--src tokens] <value>...   e.g. '#646cff' 20px 1.5rem

import fs from 'node:fs';
import path from 'node:path';

const FILES = {
  global: { file: 'global.json', root: 'global tokens', level: 'global' },
  system: { file: 'system-light.json', root: 'system tokens', level: 'system' },
  dark: { file: 'system-dark.json', root: 'system tokens', level: 'dark', optional: true },
  component: { file: 'components.json', root: 'components tokens', level: 'component' },
};
const REF_ROOTS = { global: 'global tokens', system: 'system tokens', components: 'components tokens' };
const LEVEL_OF_ROOT = { 'global tokens': 'global', 'system tokens': 'system', 'components tokens': 'component' };
const REFERENCE = /^\{(.+)\}$/;
const HEX_COLOR = /^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/;
const TYPES = new Set(['color', 'number', 'string']);
const TOKEN_KEYS = new Set(['$type', '$value', '$description']);
// Numbers under these path words are lengths and get a unit; everything else stays unitless.
const UNIT_WORDS = ['font-size', 'line-height', 'spacing', 'sizing', 'radius', 'width', 'height', 'offset'];
const GENERATED_MARKER = 'GENERATED by quantum-tokens';
const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', 'build', 'out', '.next', '.nuxt', '.astro',
  '.svelte-kit', '.turbo', '.vercel', 'coverage', 'storybook-static', 'Pods', 'DerivedData']);
const STYLE_EXT = new Set(['.css', '.scss', '.sass', '.less', '.styl', '.vue', '.svelte', '.astro']);
const SCRIPT_EXT = new Set(['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.html', '.mdx']);
const TOKEN_USAGE = /--(?:components|system|global)-tokens--[a-z0-9-]+/g;
const IGNORE_COMMENT = 'quantum-tokens-ignore';
// Info findings print this many examples unless --verbose; a fresh seed has hundreds.
const INFO_EXAMPLES = 10;

// ---------- args ----------

function parseArgs(argv) {
  const [command, ...rest] = argv;
  const opts = { command, scan: [], exempt: [], values: [] };
  for (let i = 0; i < rest.length; i++) {
    const arg = rest[i];
    if (!arg.startsWith('--')) {
      if (command !== 'match') fail(`Unexpected argument "${arg}".`);
      opts.values.push(arg);
      continue;
    }
    const key = arg.slice(2);
    if (key === 'strict' || key === 'verbose') { opts[key] = true; continue; }
    const value = rest[++i];
    if (value === undefined) fail(`Missing value for ${arg}.`);
    if (key === 'scan' || key === 'exempt') opts[key].push(value);
    else opts[key] = value;
  }
  opts.src ??= 'tokens';
  opts.out ??= path.join(opts.src, 'design-tokens.css');
  return opts;
}

function fail(message) {
  console.error(`✖ ${message}`);
  process.exit(1);
}

// ---------- load + flatten ----------

function loadSources(src) {
  if (!fs.existsSync(src)) fail(`Token directory "${src}" not found. Pass --src <dir>.`);
  const out = {};
  for (const [key, spec] of Object.entries(FILES)) {
    const file = path.join(src, spec.file);
    if (!fs.existsSync(file)) {
      if (spec.optional) { out[key] = {}; continue; }
      fail(`Missing ${file}. Seed it from the skill's assets/tokens/${spec.file}.`);
    }
    try {
      out[key] = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (error) {
      fail(`${file} is not valid JSON: ${error.message}`);
    }
  }
  return out;
}

function flatten(tree, spec, problems) {
  const tokens = new Map();
  const visit = (node, keys) => {
    if (!node || typeof node !== 'object' || Array.isArray(node)) {
      problems.push(issue('format', 'error', `${spec.file} › ${keys.join('.')}: expected a token or group object.`));
      return;
    }
    const where = `${spec.file} › ${keys.join('.')}`;
    if (typeof node.$type === 'string' && node.$value !== undefined) {
      for (const k of Object.keys(node)) {
        if (!TOKEN_KEYS.has(k)) problems.push(issue('format', 'error', `${where}: "${k}" is not allowed — tokens hold only $type, $value, $description.`));
      }
      const tokenPath = [spec.root, ...keys].join('.');
      const ref = typeof node.$value === 'string' ? node.$value.match(REFERENCE)?.[1] : undefined;
      const token = { path: tokenPath, level: spec.level, file: spec.file, type: node.$type, value: node.$value, ref, description: node.$description };
      checkFormat(token, where, problems);
      tokens.set(tokenPath, token);
      return;
    }
    for (const k of Object.keys(node)) {
      if (k.startsWith('$')) {
        if (k !== '$description') problems.push(issue('format', 'error', `${where}: group key "${k}" is not allowed (slim DTCG: no $extensions or tool metadata).`));
        continue;
      }
      if (/[.{}]/.test(k)) problems.push(issue('format', 'error', `${where}: key "${k}" contains ".", "{" or "}", which breaks reference paths.`));
      visit(node[k], [...keys, k]);
    }
  };
  for (const k of Object.keys(tree)) {
    if (k.startsWith('$')) continue;
    visit(tree[k], [k]);
  }
  return tokens;
}

function checkFormat(token, where, problems) {
  if (!TYPES.has(token.type)) {
    problems.push(issue('format', 'error', `${where}: $type "${token.type}" is not one of color, number, string.`));
    return;
  }
  if (token.ref) {
    if (/\{|\}/.test(token.ref)) problems.push(issue('format', 'error', `${where}: a reference must be the entire value — no composition.`));
    return;
  }
  if (typeof token.value === 'string' && token.value.includes('{')) {
    problems.push(issue('format', 'error', `${where}: "${token.value}" mixes a reference with other text — references must be the entire value.`));
  }
  if (token.type === 'number' && typeof token.value !== 'number') {
    problems.push(issue('format', 'error', `${where}: number token holds "${token.value}". Drop the unit, or make it a string if the unit is not px.`));
  }
  if (token.type === 'color' && !HEX_COLOR.test(String(token.value))) {
    problems.push(issue('format', 'error', `${where}: color "${token.value}" must be #RRGGBB or #RRGGBBAA.`));
  }
}

// ---------- resolve ----------

function targetPath(ref) {
  const dot = ref.indexOf('.');
  const root = dot === -1 ? undefined : REF_ROOTS[ref.slice(0, dot)];
  return root ? `${root}.${ref.slice(dot + 1)}` : undefined;
}

function resolve(space, token, seen = []) {
  if (!token.ref) return { value: token.value };
  const target = targetPath(token.ref);
  const next = target && space.get(target);
  if (!next) return { error: `references {${token.ref}}, which does not exist${suggest(space, target)}` };
  if (seen.includes(next.path)) return { error: `reference cycle: ${[...seen, next.path].join(' → ')}` };
  return resolve(space, next, [...seen, token.path]);
}

function suggest(space, target) {
  if (!target) return ' (the prefix must be global, system or components).';
  const lower = target.toLowerCase();
  for (const key of space.keys()) {
    if (key.toLowerCase() !== lower) continue;
    const prefix = Object.keys(REF_ROOTS).find((k) => REF_ROOTS[k] === key.slice(0, key.indexOf('.')));
    return `. Keys are case-sensitive — did you mean {${prefix}.${stripRoot(key)}}?`;
  }
  return '.';
}

function buildModel(src) {
  const raw = loadSources(src);
  const problems = [];
  const maps = {};
  for (const [key, spec] of Object.entries(FILES)) maps[key] = flatten(raw[key], spec, problems);

  const light = new Map([...maps.global, ...maps.system, ...maps.component]);
  const dark = new Map([...maps.global, ...maps.dark]);
  const resolved = new Map();
  const resolveInto = (space, token, keyPrefix) => {
    const result = resolve(space, token);
    if (result.error) {
      problems.push(issue('broken-reference', 'error', `${token.file} › ${stripRoot(token.path)} ${result.error}`));
      return;
    }
    resolved.set(keyPrefix + token.path, result.value);
  };
  for (const token of light.values()) resolveInto(light, token, '');
  for (const token of maps.dark.values()) {
    if (!maps.system.has(token.path)) {
      problems.push(issue('broken-reference', 'error', `system-dark.json › ${stripRoot(token.path)} has no counterpart in system-light.json.`));
    }
    if (token.type !== 'color') {
      problems.push(issue('format', 'error', `system-dark.json › ${stripRoot(token.path)} is a ${token.type} — the dark file overrides colors only.`));
    }
    resolveInto(dark, token, 'dark:');
  }
  return { maps, light, dark, resolved, problems };
}

function stripRoot(tokenPath) {
  return tokenPath.slice(tokenPath.indexOf('.') + 1);
}

// ---------- naming + formatting ----------

function cssName(tokenPath) {
  return '--' + tokenPath.toLowerCase().replace(/\s+/g, '-').replace(/\./g, '--').replace(/[^a-z0-9-]/g, '');
}

function formatValue(type, value, tokenPath) {
  if (type === 'color') {
    const hex = String(value);
    return /^#[0-9a-fA-F]{6}ff$/i.test(hex) ? hex.slice(0, 7) : hex;
  }
  if (type === 'number') {
    const n = Math.round(Number(value) * 10000) / 10000; // drops design-tool float noise
    const segments = tokenPath.toLowerCase().split('.');
    const isRatio = segments.includes('scale');
    const lower = tokenPath.toLowerCase();
    return !isRatio && n !== 0 && UNIT_WORDS.some((w) => lower.includes(w)) ? `${n}px` : String(n);
  }
  return String(value);
}

function declaration(model, token, space, keyPrefix = '') {
  const target = token.ref && space.get(targetPath(token.ref));
  if (token.level === 'component' && target && target.level !== 'global') {
    return `  ${cssName(token.path)}: var(${cssName(target.path)});`;
  }
  const value = model.resolved.get(keyPrefix + token.path);
  if (value === undefined) return `  /* unresolved: ${cssName(token.path)} */`;
  return `  ${cssName(token.path)}: ${formatValue(token.type, value, token.path)};`;
}

// ---------- build ----------

function build(opts) {
  const model = buildModel(opts.src);
  const errors = model.problems.filter((p) => p.severity === 'error');
  if (errors.length) {
    printIssues(errors, opts);
    fail(`${errors.length} error(s) — nothing written. Fix the JSON and rebuild.`);
  }
  const { maps, light, dark } = model;
  const systemTokens = [...maps.system.values()];
  const block = (title, tokens, space, keyPrefix) =>
    [`  /* ${title} */`, ...tokens.map((t) => declaration(model, t, space, keyPrefix))].join('\n');

  const css = [
    `/* ${GENERATED_MARKER} build from ${opts.src}/*.json — do not edit. Run the token build instead. */`,
    '',
    ':root {',
    block('Global tokens', [...maps.global.values()], light),
    '',
    block('System tokens (non-color)', systemTokens.filter((t) => t.type !== 'color'), light),
    '}',
    '',
    '/* Component tokens alias system variables, so they re-resolve in every themed scope. */',
    ':root, [data-theme] {',
    block('Component tokens', [...maps.component.values()], light),
    '}',
    '',
    ':root, [data-theme="light"] {',
    block('System color tokens — light', systemTokens.filter((t) => t.type === 'color'), light),
    '}',
    '',
    '[data-theme="dark"] {',
    block('System color tokens — dark overrides', [...maps.dark.values()], dark, 'dark:'),
    '}',
    '',
  ].join('\n');

  fs.mkdirSync(path.dirname(opts.out), { recursive: true });
  fs.writeFileSync(opts.out, css);
  const lightColors = systemTokens.filter((t) => t.type === 'color').length;
  console.log(`✔ Wrote ${opts.out}`);
  console.log(`  global ${maps.global.size} · system ${maps.system.size} · component ${maps.component.size} · dark overrides ${maps.dark.size}/${lightColors} system colors`);
  console.log('  0 unresolved references');
}

// ---------- audit ----------

function issue(check, severity, message, location) {
  return { check, severity, message, location };
}

function walk(dir, exempt, files = []) {
  if (!fs.existsSync(dir)) return files;
  const stat = fs.statSync(dir);
  if (stat.isFile()) { files.push(dir); return files; }
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') && entry.name !== '.') continue;
    const full = path.join(dir, entry.name);
    if (exempt.some((e) => full === e || full.startsWith(e + path.sep))) continue;
    if (entry.isDirectory()) { if (!SKIP_DIRS.has(entry.name)) walk(full, exempt, files); }
    else if (STYLE_EXT.has(path.extname(entry.name)) || SCRIPT_EXT.has(path.extname(entry.name))) files.push(full);
  }
  return files;
}

const COLOR_IN_STYLE = /(^|[\s:,(])#[0-9a-fA-F]{3,8}\b|\b(?:rgba?|hsla?|oklch|oklab|lab|lch|hwb)\(/;
const COLOR_IN_SCRIPT = /(['"`])#[0-9a-fA-F]{3,8}\1|(['"`])(?:rgba?|hsla?|oklch)\(/;
const DECLARATION = /^\s*([a-z-]+)\s*:\s*(.+?)\s*$/;
// Properties whose lengths come from the Spacing, Border radius and type scales.
const LENGTH_PROPS = /^(padding|margin|gap|row-gap|column-gap|font-size|letter-spacing|border-radius|border-(?:top|bottom)-(?:left|right)-radius)(-[a-z-]+)?$/;
const UNITLESS_PROPS = /^(line-height|font-weight)$/;
const LENGTH = /(^|[^\w.-])-?\d*\.?\d+(px|rem|em|pt|ch|vh|vw|vmin|vmax)\b/;
const BARE_NUMBER = /(^|[^\w.-])-?\d*\.?\d+(?![\w%])/;
const DEMO_FILE = /\.(stories|story|test|spec)\.[a-z]+$/;

function scanUsages(opts, srcDir, outFile) {
  const roots = opts.scan.length ? opts.scan : [fs.existsSync('src') ? 'src' : '.'];
  const exempt = [...opts.exempt, srcDir].map((p) => path.normalize(p));
  const usages = [];
  const hardcoded = [];
  for (const root of roots) {
    for (const file of walk(path.normalize(root), exempt)) {
      if (path.resolve(file) === path.resolve(outFile) || DEMO_FILE.test(file)) continue;
      const text = fs.readFileSync(file, 'utf8');
      if (text.slice(0, 300).includes(GENERATED_MARKER)) continue;
      const isStyle = STYLE_EXT.has(path.extname(file));
      let inBlockComment = false;
      text.split('\n').forEach((line, i) => {
        const location = `${file}:${i + 1}`;
        for (const match of line.matchAll(TOKEN_USAGE)) {
          if (match[0].endsWith('-') || line[match.index + match[0].length] === '$') continue; // dynamic name
          usages.push({ name: match[0], location });
        }
        if (line.includes(IGNORE_COMMENT)) return;
        let code = line;
        if (inBlockComment) {
          const end = code.indexOf('*/');
          if (end === -1) return;
          code = code.slice(end + 2);
          inBlockComment = false;
        }
        code = code.replace(/\/\*.*?\*\//g, '');
        if (code.includes('/*')) { code = code.slice(0, code.indexOf('/*')); inBlockComment = true; }
        if (isStyle) code = code.replace(/(^|\s)\/\/.*$/, '');
        if (isStyle ? COLOR_IN_STYLE.test(code) : COLOR_IN_SCRIPT.test(code)) {
          hardcoded.push(issue('hardcoded', 'warning', `raw color: ${code.trim()}`, location));
          return;
        }
        if (!isStyle) return;
        for (const segment of code.split(/[;{}]/)) {
          const decl = segment.match(DECLARATION);
          if (!decl) continue;
          const [, prop, value] = decl;
          const literal = stripVars(value).replace(/\b0(px|rem|em)?\b/g, '');
          const raw = (LENGTH_PROPS.test(prop) && LENGTH.test(literal))
            || (UNITLESS_PROPS.test(prop) && BARE_NUMBER.test(literal))
            || (prop === 'font-family' && !/var\(|inherit/.test(value));
          if (raw) hardcoded.push(issue('hardcoded', 'warning', `raw ${prop}: ${value}`, location));
        }
      });
    }
  }
  return { usages, hardcoded };
}

function stripVars(value) {
  let out = value;
  let previous;
  do { previous = out; out = out.replace(/var\([^()]*\)/g, ''); } while (out !== previous);
  return out;
}

function audit(opts) {
  const model = buildModel(opts.src);
  const { maps, light } = model;
  const issues = [...model.problems];
  const levelRule = (token, message) =>
    issues.push(issue('raw-value', 'warning', `${token.file} › ${stripRoot(token.path)}: ${message}`));
  const targetLevel = (token) => token.ref && light.get(targetPath(token.ref))?.level;

  for (const token of maps.global.values()) {
    if (token.ref) levelRule(token, 'global tokens hold raw values only, never references.');
  }
  for (const [map, isDark] of [[maps.system, false], [maps.dark, true]]) {
    for (const token of map.values()) {
      if (!token.ref) {
        if (token.type === 'color') levelRule(token, isDark ? 'raw hex in the dark file — add the shade to global.json and reference it.' : 'raw color — system colors must reference a global token.');
        else if (!token.description) levelRule(token, 'raw value without a $description — reference a global token or document why there is none.');
      } else if (token.ref.split('.')[0] !== 'global') {
        levelRule(token, `references {${token.ref}} — system tokens reference global tokens only.`);
      }
    }
  }
  for (const token of maps.component.values()) {
    if (!token.ref) {
      if (token.type === 'color') levelRule(token, 'raw color — component colors must reference a system token.');
      else if (!token.description) levelRule(token, 'raw value without a $description — reference a system token or document why there is none.');
    } else if (targetLevel(token) === 'global') {
      levelRule(token, `skips a level: references {${token.ref}} instead of a system token.`);
    } else if (targetLevel(token) === 'component') {
      levelRule(token, `references another component token {${token.ref}} — point it at the system token directly.`);
    }
  }

  const { usages, hardcoded } = scanUsages(opts, path.normalize(opts.src), opts.out);
  const defined = new Set([...light.values()].map((t) => cssName(t.path)));
  const used = new Set();
  for (const { name, location } of usages) {
    used.add(name);
    const isPrefix = !defined.has(name) && [...defined].some((d) => d.startsWith(name + '--'));
    if (!defined.has(name) && !isPrefix) issues.push(issue('missing-token', 'error', `${name} is not defined in any token JSON.`, location));
    else if (!name.startsWith('--components-tokens--')) issues.push(issue('bad-usage', 'warning', `${name} — UI code must use a component token.`, location));
  }
  issues.push(...hardcoded);

  const referenced = new Set();
  for (const token of [...maps.system.values(), ...maps.dark.values(), ...maps.component.values()]) {
    if (token.ref) referenced.add(targetPath(token.ref));
  }
  for (const token of maps.global.values()) {
    if (!referenced.has(token.path)) issues.push(issue('unused', 'info', `global ${stripRoot(token.path)} — no system token references it.`));
  }
  for (const token of maps.system.values()) {
    if (!referenced.has(token.path)) issues.push(issue('unused', 'info', `system ${stripRoot(token.path)} — no component token references it.`));
  }
  for (const token of maps.component.values()) {
    if (!used.has(cssName(token.path))) issues.push(issue('unused', 'info', `${cssName(token.path)} — not used in scanned code.`));
  }

  const groups = new Map();
  for (const token of light.values()) {
    if (token.level === 'global') continue; // global scales overlap by design (Sizing.8 = Border radius.8)
    const value = model.resolved.get(token.path);
    if (value === undefined) continue;
    const key = `${token.level}|${token.type}|${String(value).toLowerCase()}`;
    groups.set(key, [...(groups.get(key) ?? []), stripRoot(token.path)]);
  }
  for (const [key, paths] of groups) {
    if (paths.length < 2) continue;
    const [level, type, value] = key.split('|');
    issues.push(issue('duplicate', 'info', `${paths.length} ${level} ${type} tokens resolve to ${value}: ${paths.slice(0, 4).join(', ')}${paths.length > 4 ? ', …' : ''}`));
  }

  const lightColors = [...maps.system.values()].filter((t) => t.type === 'color');
  const missingDark = lightColors.filter((t) => !maps.dark.has(t.path)).length;
  if (missingDark) issues.push(issue('dark-coverage', 'info', `${missingDark}/${lightColors.length} light system colors have no dark override and inherit the light value.`));

  printIssues(issues, opts);
  const counts = { error: 0, warning: 0, info: 0 };
  for (const i of issues) counts[i.severity]++;
  console.log(`\n${counts.error} error(s) · ${counts.warning} warning(s) · ${counts.info} info · scanned usages: ${usages.length}`);
  if (counts.error || (opts.strict && counts.warning)) process.exit(1);
}

function printIssues(issues, opts) {
  const order = ['format', 'broken-reference', 'missing-token', 'bad-usage', 'raw-value', 'hardcoded', 'duplicate', 'unused', 'dark-coverage'];
  const icon = { error: '✖', warning: '▲', info: '·' };
  for (const check of order) {
    const list = issues.filter((i) => i.check === check);
    if (!list.length) continue;
    console.log(`\n${icon[list[0].severity]} ${check} (${list[0].severity}) — ${list.length}`);
    const shown = list[0].severity === 'info' && !opts.verbose ? list.slice(0, INFO_EXAMPLES) : list;
    for (const i of shown) console.log(`  ${i.location ? i.location + '  ' : ''}${i.message}`);
    if (shown.length < list.length) console.log(`  … ${list.length - shown.length} more (--verbose)`);
  }
}

// ---------- match ----------

const REM_PX = 16;
// System groups a raw length can map to, keyed by the role the length plays.
const LENGTH_GROUPS = ['Spacing', 'Sizing', 'Border radius', 'Typography.font-size', 'Typography.Line-height'];

function parseColor(input) {
  const v = input.trim().toLowerCase();
  let m = v.match(/^#([0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/);
  if (m) {
    let h = m[1];
    if (h.length <= 4) h = [...h].map((c) => c + c).join('');
    return { rgb: [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)), alpha: h.length === 8 ? parseInt(h.slice(6), 16) / 255 : 1 };
  }
  m = v.match(/^rgba?\(\s*([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)(?:[\s,/]+([\d.]+%?))?\s*\)$/);
  if (m) {
    const a = m[4] === undefined ? 1 : m[4].endsWith('%') ? parseFloat(m[4]) / 100 : parseFloat(m[4]);
    return { rgb: [m[1], m[2], m[3]].map(Number), alpha: a };
  }
  return undefined;
}

function toLab([r, g, b]) {
  const lin = (c) => { c /= 255; return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4; };
  const [R, G, B] = [lin(r), lin(g), lin(b)];
  const xyz = [(R * 0.4124 + G * 0.3576 + B * 0.1805) / 0.95047, R * 0.2126 + G * 0.7152 + B * 0.0722, (R * 0.0193 + G * 0.1192 + B * 0.9505) / 1.08883];
  const f = (t) => (t > 0.008856 ? Math.cbrt(t) : 7.787 * t + 16 / 116);
  const [fx, fy, fz] = xyz.map(f);
  return [116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)];
}

function deltaE(a, b) {
  const [la, lb] = [toLab(a), toLab(b)];
  return Math.hypot(la[0] - lb[0], la[1] - lb[1], la[2] - lb[2]);
}

function parseLength(input) {
  const m = input.trim().match(/^(-?\d*\.?\d+)(px|rem)?$/);
  if (!m) return undefined;
  return parseFloat(m[1]) * (m[2] === 'rem' ? REM_PX : 1);
}

function match(opts) {
  if (!opts.values.length) fail("Usage: quantum-tokens.mjs match [--src tokens] <value>...  e.g. '#646cff' 20px 1.5rem");
  const model = buildModel(opts.src);
  const resolvedTokens = (map) => [...map.values()]
    .map((t) => ({ t, value: model.resolved.get(t.path) }))
    .filter((x) => x.value !== undefined);
  for (const input of opts.values) {
    console.log(`\n${input}`);
    const color = parseColor(input);
    if (color) {
      const rank = (map) => resolvedTokens(map)
        .filter(({ t }) => t.type === 'color')
        .map(({ t, value }) => ({ t, value, c: parseColor(String(value)) }))
        .map((x) => ({ ...x, d: deltaE(color.rgb, x.c.rgb) + Math.abs(color.alpha - x.c.alpha) * 100 }))
        .sort((a, b) => a.d - b.d)
        .slice(0, 5);
      for (const [label, map] of [['system', model.maps.system], ['global', model.maps.global]]) {
        for (const { t, value, d } of rank(map)) {
          console.log(`  ${label.padEnd(6)}  ${stripRoot(t.path).padEnd(52)} ${String(value).padEnd(10)} ΔE ${d.toFixed(1)}`);
        }
      }
      continue;
    }
    const px = parseLength(input);
    if (px === undefined) { console.log('  not a color (#hex, rgb()) or length (px, rem, number)'); continue; }
    for (const group of LENGTH_GROUPS) {
      const candidates = resolvedTokens(model.maps.system)
        .filter(({ t }) => t.type === 'number' && stripRoot(t.path).startsWith(group + '.') && !/\.(Base|Scale)$/.test(t.path))
        .map(({ t, value }) => ({ t, value: Number(value), d: Math.abs(Number(value) - px) }))
        .sort((a, b) => a.d - b.d)
        .slice(0, 2);
      const line = candidates.map(({ t, value, d }) => `${stripRoot(t.path)} = ${value}${d ? ` (off by ${+d.toFixed(2)})` : ' ✓ exact'}`).join('  ·  ');
      console.log(`  ${group.padEnd(22)} ${line}`);
    }
  }
}

// ---------- main ----------

const opts = parseArgs(process.argv.slice(2));
if (opts.command === 'build') build(opts);
else if (opts.command === 'audit') audit(opts);
else if (opts.command === 'match') match(opts);
else fail('Usage: quantum-tokens.mjs <build|audit|match> [--src tokens] [--out file.css] [--scan dir]... [--exempt path]... [--strict] [--verbose] [values...]');
